= Java 9 - O que é realmente bom, e o que não é
SouJava <https://soujava.org.br/>

== Colaboradores
Esse material está sendo traduzido. E para isso, conta com a colaboração de:

Nome: Cesar Nogueira              Github -
Nome: Thiago Nascimento           Github: https://github.com/thiagonascimentorj

== Introdução

Este repositório contém uma apresentação com RevelJS e tenta dar uma visão geral
sobre as melhorias que virão com Java 9 para a plataforma Java.

Baseado no estado atual de 2017-05-29

== Conteúdo

[cols="1,3"]
|===
|`presentation`         | A short RevealJS based presentation. Just open `index.html`
|`playground`           | Código de exemplo.
|`playground-dependent` | Outro módulo Jigsaw que depende da pasta `playground` e demonstra Service Provider com módulos.      
|`run-with-modules`     | Script Bash demonstrando como compilar e rodar o exemplo com módulos usando já os novos comandos do Java9 para CMD
|===

== Como começar
1. Instale o Java 9 EAP
2. Verifique se os caminhos `JAVA_HOME` e `PATH` apontam para a instalação do Java 9
3. Abra o projeto com IntelliJ IDEA 2016.2+ ou rode `run-with-modules`

----
$ env | grep JAVA_HOME
JAVA_HOME=/usr/lib/jvm/java-9-oracle
$ javac -version
javac 9-ea
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+123)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+123, mixed mode)
----

